# Generated by Django 4.1.3 on 2022-11-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'My Subscribers', 'verbose_name_plural': 'A lot of Subscribers'},
        ),
    ]
