# Generated by Django 4.1.4 on 2023-01-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчика', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
