# Generated by Django 4.1.3 on 2022-11-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_productinorder_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='number',
            new_name='num',
        ),
    ]
