# Generated by Django 4.1.3 on 2022-11-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_number_productinorder_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='num',
            new_name='nmb',
        ),
    ]
