# Generated by Django 4.1.3 on 2022-11-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_num_productinorder_nmb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='order_total_price',
        ),
    ]
