# Generated by Django 4.1.4 on 2022-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_productinbasket_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='image',
            field=models.ImageField(default=None, upload_to='media/products_images/'),
        ),
    ]
