# Generated by Django 4.1.4 on 2022-12-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_productinbasket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='image',
        ),
    ]
