# Generated by Django 4.1.3 on 2022-11-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategory_product_discount_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
    ]
