# Generated by Django 4.1.4 on 2023-01-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
