# Generated by Django 4.1.4 on 2023-01-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_camera_product_spec_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spec_1',
            new_name='specfive',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_2',
            new_name='specfour',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_3',
            new_name='specone',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_4',
            new_name='specthree',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='spec_5',
            new_name='spectwo',
        ),
    ]
